api_platform:
    title: 'PROJET FIL ROUGE'
    description: 'A Symfony API to manage a simple blog app.'
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    # patch_formats:
    #     json: ['application/merge-patch+json']
    formats:
        json: ['application/json']
    swagger:
        versions: [3]

    collection:
        pagination:
            # items_per_page: 20 # Default value
